# Catppuccin Mocha Theme for Starship
# Dark theme optimized for eye care and reduced eye strain
format = "$all$character"
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
# Base colors - Dark theme for eye comfort
background = "#1e1e2e"
foreground = "#cdd6f4"
current_line = "#313244"

# Accent colors - Soft and eye-friendly
mauve = "#cba6f7"      # Primary accent - Gentle purple
blue = "#89b4fa"       # Secondary accent - Soft blue
green = "#a6e3a1"      # Success - Natural green
red = "#f38ba8"        # Error - Soft red
yellow = "#f9e2af"      # Warning - Warm yellow
teal = "#94e2d5"       # Info - Calm teal
peach = "#fab387"       # Highlight - Soft orange

# Extended palette for better variety
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
maroon = "#eba0ac"
red_alt = "#f38ba8"
orange = "#fab387"
yellow_alt = "#f9e2af"
green_alt = "#a6e3a1"
teal_alt = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue_alt = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
