# Catppuccin Latte Theme for Starship
# Light theme optimized for eye care and reduced eye strain
format = "$all$character"
palette = "catppuccin_latte"

[palettes.catppuccin_latte]
# Base colors - Light theme for eye comfort
background = "#eff1f5"
foreground = "#4c4f69"
current_line = "#e6e9ef"

# Accent colors - Soft and eye-friendly
mauve = "#8839ef"      # Primary accent - Soft purple
blue = "#1e66f5"       # Secondary accent - Gentle blue
green = "#40a02b"      # Success - Natural green
red = "#d20f39"        # Error - Soft red
yellow = "#df8e1d"      # Warning - Warm yellow
teal = "#179299"       # Info - Calm teal
peach = "#fe640b"      # Highlight - Soft orange

# Extended palette - Eye-friendly light colors
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
maroon = "#e64553"
red_alt = "#d20f39"
orange = "#fe640b"
yellow_alt = "#df8e1d"
green_alt = "#40a02b"
teal_alt = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue_alt = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
